#Makefile
# TODO better makefile

all:
	gcc -g -DDEBUG -DINFO ./parser_expr_test.c ./../../src/parser_expr.c ./../../src/fake_lex.c ./../../src/token.c ./../../src/ast.c ./../../src/g_stack.c ./../../src/ast_stack.c -o tester
